// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWN8fMFHp-PFXbY9Duu0uDsXJ-_DGSI9w',
    appId: '1:258656413911:android:bfa88e695cffd921626892',
    messagingSenderId: '258656413911',
    projectId: 'socialified-23223',
    databaseURL: 'https://socialified-23223-default-rtdb.firebaseio.com',
    storageBucket: 'socialified-23223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySU4h66tkg3OujTVtkOH3T3DGrslTjxc',
    appId: '1:258656413911:ios:ba8fa463ce215c3a626892',
    messagingSenderId: '258656413911',
    projectId: 'socialified-23223',
    databaseURL: 'https://socialified-23223-default-rtdb.firebaseio.com',
    storageBucket: 'socialified-23223.appspot.com',
    androidClientId: '258656413911-2remp44bce4418rojsebhda5o26v5k44.apps.googleusercontent.com',
    iosClientId: '258656413911-6kjfjodfh56v2otkjqs5htfpmnl4m8qr.apps.googleusercontent.com',
    iosBundleId: 'com.baljit.apptesting',
  );
}
